//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace duplicateFile.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("duplicateFile.Resources.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        internal static string adr {
            get {
                return ResourceManager.GetString("adr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Checksum calculés.
        /// </summary>
        internal static string CalculatedHash {
            get {
                return ResourceManager.GetString("CalculatedHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé le.
        /// </summary>
        internal static string created {
            get {
                return ResourceManager.GetString("created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée de accés à la base de données.
        /// </summary>
        internal static string DataBaseAccessDuration {
            get {
                return ResourceManager.GetString("DataBaseAccessDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichiers effacés.
        /// </summary>
        internal static string DeletedFiles {
            get {
                return ResourceManager.GetString("DeletedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille des fichiers dupliqués.
        /// </summary>
        internal static string DuplicateFileSize {
            get {
                return ResourceManager.GetString("DuplicateFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée de l&apos;analyse (en seconde).
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de fin.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string Erreur {
            get {
                return ResourceManager.GetString("Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur à la conversion de {0} :
        ///{1}.
        /// </summary>
        internal static string Error_Conversion {
            get {
                return ResourceManager.GetString("Error_Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur à la création de la tâche\nVérifiez le nom d&apos;utilisateur et le mot de passe.
        /// </summary>
        internal static string Error_Creation_tache {
            get {
                return ResourceManager.GetString("Error_Creation_tache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot; n&apos;à pu être converti
        ///.
        /// </summary>
        internal static string Error_n_a_pu_etre_converti {
            get {
                return ResourceManager.GetString("Error_n_a_pu_etre_converti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur à la connection du lecteur réseau.
        /// </summary>
        internal static string Error_Network_Drive {
            get {
                return ResourceManager.GetString("Error_Network_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom d&apos;utilisateur et le mot de passe ne peuvent être vide!.
        /// </summary>
        internal static string Error_Nom_Utilisateur_Non_Vide {
            get {
                return ResourceManager.GetString("Error_Nom_Utilisateur_Non_Vide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur pendant le renommage de :
        ///.
        /// </summary>
        internal static string Error_pendant_le_renomage {
            get {
                return ResourceManager.GetString("Error_pendant_le_renomage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur à la suppression de {0} :
        ///{1}.
        /// </summary>
        internal static string Error_Supp {
            get {
                return ResourceManager.GetString("Error_Supp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répartition des fichiers par status.
        /// </summary>
        internal static string Gr_FileByStatus {
            get {
                return ResourceManager.GetString("Gr_FileByStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evolution du nombre de fichier dupliqués.
        /// </summary>
        internal static string Gr_NumberOfDuplicateFile {
            get {
                return ResourceManager.GetString("Gr_NumberOfDuplicateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evolution du nombre total de fichier .
        /// </summary>
        internal static string Gr_NumberOfFile {
            get {
                return ResourceManager.GetString("Gr_NumberOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volume par dossier.
        /// </summary>
        internal static string GR_Size_By_Path {
            get {
                return ResourceManager.GetString("GR_Size_By_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evolution du volume de fichiers dupliqués.
        /// </summary>
        internal static string Gr_SizeOfDuplicateFileByTime {
            get {
                return ResourceManager.GetString("Gr_SizeOfDuplicateFileByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveaux fichiers dupliqués depuis la dernière analyse.
        /// </summary>
        internal static string GR_Vol_Duplique_Dern_Analyse {
            get {
                return ResourceManager.GetString("GR_Vol_Duplique_Dern_Analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Original.
        /// </summary>
        internal static string isOriginal {
            get {
                return ResourceManager.GetString("isOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernier accés.
        /// </summary>
        internal static string lastAccess {
            get {
                return ResourceManager.GetString("lastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mail.
        /// </summary>
        internal static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifié.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveaux fichiers.
        /// </summary>
        internal static string NewFiles {
            get {
                return ResourceManager.GetString("NewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Répertoires analysés.
        /// </summary>
        internal static string NumberOfDir {
            get {
                return ResourceManager.GetString("NumberOfDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichiers dupliqués.
        /// </summary>
        internal static string NumberOfDuplicateFile {
            get {
                return ResourceManager.GetString("NumberOfDuplicateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichiers analysés.
        /// </summary>
        internal static string NumberOfFile {
            get {
                return ResourceManager.GetString("NumberOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        internal static string prenom {
            get {
                return ResourceManager.GetString("prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qualifier.
        /// </summary>
        internal static string q {
            get {
                return ResourceManager.GetString("q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée de calcul de qualifier  (en seconde).
        /// </summary>
        internal static string QualifierDuration {
            get {
                return ResourceManager.GetString("QualifierDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taux d&apos;analyse (fichiers/seconde).
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de début.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tel..
        /// </summary>
        internal static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volume total analysé.
        /// </summary>
        internal static string TotalFileSize {
            get {
                return ResourceManager.GetString("TotalFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ({0} caractères).
        /// </summary>
        internal static string Txt___0__caractères_ {
            get {
                return ResourceManager.GetString("Txt___0__caractères_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} chemin(s) détecté(s).
        /// </summary>
        internal static string Txt__0__chemin_s__détecté_s_ {
            get {
                return ResourceManager.GetString("Txt__0__chemin_s__détecté_s_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} Fichiers.
        /// </summary>
        internal static string Txt_0_Fichiers {
            get {
                return ResourceManager.GetString("Txt_0_Fichiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyse (*.afd)|*.afd.
        /// </summary>
        internal static string Txt_Analyse____afd____afd {
            get {
                return ResourceManager.GetString("Txt_Analyse____afd____afd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyse des fichiers en cours....
        /// </summary>
        internal static string Txt_Analyse_des_fichiers_en_cours___ {
            get {
                return ResourceManager.GetString("Txt_Analyse_des_fichiers_en_cours___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyse des résultats.
        /// </summary>
        internal static string Txt_Analyse_des_résultats {
            get {
                return ResourceManager.GetString("Txt_Analyse_des_résultats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyse en cours....
        /// </summary>
        internal static string Txt_Analyse_en_cours___ {
            get {
                return ResourceManager.GetString("Txt_Analyse_en_cours___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyser.
        /// </summary>
        internal static string Txt_Analyser {
            get {
                return ResourceManager.GetString("Txt_Analyser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string Txt_Annuler {
            get {
                return ResourceManager.GetString("Txt_Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caracteres.
        /// </summary>
        internal static string Txt_Caracteres {
            get {
                return ResourceManager.GetString("Txt_Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement des données....
        /// </summary>
        internal static string Txt_Chargement_des_données {
            get {
                return ResourceManager.GetString("Txt_Chargement_des_données", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        internal static string Txt_Confirmation {
            get {
                return ResourceManager.GetString("Txt_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmez vous la correction du nom :
        ///.
        /// </summary>
        internal static string Txt_Confirmez_vous_la_correction {
            get {
                return ResourceManager.GetString("Txt_Confirmez_vous_la_correction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conversion en cours....
        /// </summary>
        internal static string Txt_Conversion_en_cours___ {
            get {
                return ResourceManager.GetString("Txt_Conversion_en_cours___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  correction(s) effectuée(s)..
        /// </summary>
        internal static string Txt_correction_s__effectuée_s__ {
            get {
                return ResourceManager.GetString("Txt_correction_s__effectuée_s__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créé le.
        /// </summary>
        internal static string Txt_Created {
            get {
                return ResourceManager.GetString("Txt_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phase 2/2 : recherche des doublons....
        /// </summary>
        internal static string Txt_duplicate_file_search {
            get {
                return ResourceManager.GetString("Txt_duplicate_file_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 
        ///en :
        ///.
        /// </summary>
        internal static string Txt_En {
            get {
                return ResourceManager.GetString("Txt_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer l&apos;analyse.
        /// </summary>
        internal static string Txt_Enregistrer_l_analyse {
            get {
                return ResourceManager.GetString("Txt_Enregistrer_l_analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export..
        /// </summary>
        internal static string Txt_Export {
            get {
                return ResourceManager.GetString("Txt_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export Excel/PDF.
        /// </summary>
        internal static string Txt_Export_Excel_PDF {
            get {
                return ResourceManager.GetString("Txt_Export_Excel_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Fichiers.
        /// </summary>
        internal static string Txt_Files {
            get {
                return ResourceManager.GetString("Txt_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Fichiers/s.
        /// </summary>
        internal static string Txt_Files_Seconde {
            get {
                return ResourceManager.GetString("Txt_Files_Seconde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Génération du rapport....
        /// </summary>
        internal static string Txt_Generation_Rapport {
            get {
                return ResourceManager.GetString("Txt_Generation_Rapport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phase 1/2 : énumération et qualification des fichiers....
        /// </summary>
        internal static string Txt_Getting_File_List {
            get {
                return ResourceManager.GetString("Txt_Getting_File_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        internal static string Txt_Information {
            get {
                return ResourceManager.GetString("Txt_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La base de donnee est inaccessible, son utilisation sera désactivée..
        /// </summary>
        internal static string Txt_LA_Base_est_inaccessible {
            get {
                return ResourceManager.GetString("Txt_LA_Base_est_inaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La table de correspondance a étée modifiée souhaitez vous enregistrer les modifications?.
        /// </summary>
        internal static string Txt_La_table_de_correspondance_a_étée_modifiée_souhaitez_vous_enregistrer_les_modifications_ {
            get {
                return ResourceManager.GetString("Txt_La_table_de_correspondance_a_étée_modifiée_souhaitez_vous_enregistrer_les_mod" +
                        "ifications_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernier accés.
        /// </summary>
        internal static string Txt_LastAccess {
            get {
                return ResourceManager.GetString("Txt_LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier &quot;.
        /// </summary>
        internal static string Txt_Le_fichier__ {
            get {
                return ResourceManager.GetString("Txt_Le_fichier__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le paramètre &quot;{0}&quot; n&apos;a pas une valeur correcte.
        /// </summary>
        internal static string Txt_Le_paramètre___0___n_a_pas_une_valeur_correcte {
            get {
                return ResourceManager.GetString("Txt_Le_paramètre___0___n_a_pas_une_valeur_correcte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifié le.
        /// </summary>
        internal static string Txt_Modified {
            get {
                return ResourceManager.GetString("Txt_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string Txt_Modifier {
            get {
                return ResourceManager.GetString("Txt_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Original.
        /// </summary>
        internal static string Txt_Original {
            get {
                return ResourceManager.GetString("Txt_Original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rafraichissement de l&apos;affichage....
        /// </summary>
        internal static string Txt_Rafraichissement_de_l_affichage___ {
            get {
                return ResourceManager.GetString("Txt_Rafraichissement_de_l_affichage___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remplacer par.
        /// </summary>
        internal static string Txt_Remplacer_Par {
            get {
                return ResourceManager.GetString("Txt_Remplacer_Par", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} répertoires analysés, {1} fichiers en {2}..
        /// </summary>
        internal static string Txt_Repertoire_Analyses {
            get {
                return ResourceManager.GetString("Txt_Repertoire_Analyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resultat :.
        /// </summary>
        internal static string Txt_Resultat {
            get {
                return ResourceManager.GetString("Txt_Resultat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selectionnez un fichier.
        /// </summary>
        internal static string Txt_Selectionnez_un_fichier {
            get {
                return ResourceManager.GetString("Txt_Selectionnez_un_fichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous continuez les données actuelles seront perdues. Souhaitez vous continuer?.
        /// </summary>
        internal static string Txt_Si_vous_continuez_les_données_actuelles_seront_perdues__Souhaitez_vous_continuer_ {
            get {
                return ResourceManager.GetString("Txt_Si_vous_continuez_les_données_actuelles_seront_perdues__Souhaitez_vous_contin" +
                        "uer_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suppression des fichiers en cours....
        /// </summary>
        internal static string Txt_Suppression_des_fichiers_en_cours___ {
            get {
                return ResourceManager.GetString("Txt_Suppression_des_fichiers_en_cours___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tout les fichiers (*.*)|*.*.
        /// </summary>
        internal static string Txt_Tout_Fichiers {
            get {
                return ResourceManager.GetString("Txt_Tout_Fichiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur.
        /// </summary>
        internal static string Txt_User {
            get {
                return ResourceManager.GetString("Txt_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à vous êtes sur le point de supprimer definitivement le(s) fichier(s)! Confirmez vous cette opération?.
        /// </summary>
        internal static string Txt_vous_êtes_sur_le_point_de_supprimer_definitivement_le_s__fichier_s___Confirmez_vous_cette_opération_ {
            get {
                return ResourceManager.GetString("Txt_vous_êtes_sur_le_point_de_supprimer_definitivement_le_s__fichier_s___Confirme" +
                        "z_vous_cette_opération_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
    }
}
